name: Build and Test Backend & Frontend
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            anmolmittal/secondbrain-backend:${{ github.sha }}
            anmolmittal/secondbrain-backend:latest
      - name: Build and push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            anmolmittal/secondbrain-frontend:${{ github.sha }}
            anmolmittal/secondbrain-frontend:latest
      - name: Deploy to DigitalOcean VM
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@${{ secrets.DO_HOST }} <<EOF
            docker pull anmolmittal/secondbrain-backend:latest
            docker pull anmolmittal/secondbrain-frontend:latest

            docker rm -f secondbrain-backend || true
            docker rm -f secondbrain-frontend || true

            echo "MONGO_URI=${{ secrets.MONGO_URI }}" > backend.env

            docker run -d \
            --name secondbrain-backend \
            --env-file backend.env \
            -p 3000:3000 \
            --restart always \
            anmolmittal/secondbrain-backend:latest

            docker run -d \
            --name secondbrain-frontend \
            -p 80:5173 \
            --restart always \
            anmolmittal/secondbrain-frontend:latest
            EOF